//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstacionamentoApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EstacionamentoApp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Carro foi estacionado na vaga de Carro.
        ///.
        /// </summary>
        internal static string msgCarroEstacionadoVagaCarro {
            get {
                return ResourceManager.GetString("msgCarroEstacionadoVagaCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Carro foi estacionado na vaga de Van.
        ///.
        /// </summary>
        internal static string msgCarroEstacionadoVagaVan {
            get {
                return ResourceManager.GetString("msgCarroEstacionadoVagaVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Carro foi retirado da vaga de Carro.
        ///.
        /// </summary>
        internal static string msgCarroRetiradoVagaCarro {
            get {
                return ResourceManager.GetString("msgCarroRetiradoVagaCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Carro foi retirado da vaga de Van.
        ///.
        /// </summary>
        internal static string msgCarroRetiradoVagaVan {
            get {
                return ResourceManager.GetString("msgCarroRetiradoVagaVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vamos configurar a quantidade de vagas do estacionamento:.
        /// </summary>
        internal static string msgConfigurarEstacionamento {
            get {
                return ResourceManager.GetString("msgConfigurarEstacionamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o número do serviço desejado: .
        /// </summary>
        internal static string msgDigiteNumeroServico {
            get {
                return ResourceManager.GetString("msgDigiteNumeroServico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------.
        /// </summary>
        internal static string msgDivisao {
            get {
                return ResourceManager.GetString("msgDivisao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estacionamento está cheio.
        ///.
        /// </summary>
        internal static string msgEstacinamentoCheio {
            get {
                return ResourceManager.GetString("msgEstacinamentoCheio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///O estacionamento possui um total de {0} vaga(s) (considerando ocupadas e vazias), sendo:&quot;.
        /// </summary>
        internal static string msgEstacionamentoPossuiTotal {
            get {
                return ResourceManager.GetString("msgEstacionamentoPossuiTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** O estacionamento está vazio.
        /// </summary>
        internal static string msgEstacionamentoVazio {
            get {
                return ResourceManager.GetString("msgEstacionamentoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Estacionar carro.
        /// </summary>
        internal static string msgEstacionarCarro {
            get {
                return ResourceManager.GetString("msgEstacionarCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Estacionar moto.
        /// </summary>
        internal static string msgEstacionarMoto {
            get {
                return ResourceManager.GetString("msgEstacionarMoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Estacionar van.
        /// </summary>
        internal static string msgEstacionarVan {
            get {
                return ResourceManager.GetString("msgEstacionarVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Moto foi estacionado na vaga de Carro.
        ///.
        /// </summary>
        internal static string msgMotoEstacionadaVagaCarro {
            get {
                return ResourceManager.GetString("msgMotoEstacionadaVagaCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Moto foi estacionado na vaga de Moto.
        ///.
        /// </summary>
        internal static string msgMotoEstacionadaVagaMoto {
            get {
                return ResourceManager.GetString("msgMotoEstacionadaVagaMoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Moto foi estacionado na vaga de Van.
        ///.
        /// </summary>
        internal static string msgMotoEstacionadaVagaVan {
            get {
                return ResourceManager.GetString("msgMotoEstacionadaVagaVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Moto foi retirado da vaga de Carro.
        ///.
        /// </summary>
        internal static string msgMotoRetiradaVagaCarro {
            get {
                return ResourceManager.GetString("msgMotoRetiradaVagaCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Moto foi retirado da vaga de Moto.
        ///.
        /// </summary>
        internal static string msgMotoRetiradaVagaMoto {
            get {
                return ResourceManager.GetString("msgMotoRetiradaVagaMoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Moto foi retirado da vaga de Van.
        ///.
        /// </summary>
        internal static string msgMotoRetiradaVagaVan {
            get {
                return ResourceManager.GetString("msgMotoRetiradaVagaVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há veículos do tipo Carro para retirar.
        ///.
        /// </summary>
        internal static string msgNaoHaCarroParaRetirar {
            get {
                return ResourceManager.GetString("msgNaoHaCarroParaRetirar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há veículos do tipo Moto para retirar.
        ///.
        /// </summary>
        internal static string msgNaoHaMotoParaRetirar {
            get {
                return ResourceManager.GetString("msgNaoHaMotoParaRetirar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há vagas disponíveis para estacionar Carros.
        ///.
        /// </summary>
        internal static string msgNaoHaVagasCarro {
            get {
                return ResourceManager.GetString("msgNaoHaVagasCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há vagas disponíveis para estacionar Motos.
        ///.
        /// </summary>
        internal static string msgNaoHaVagasMoto {
            get {
                return ResourceManager.GetString("msgNaoHaVagasMoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há vagas disponíveis para estacionar Vans.
        ///.
        /// </summary>
        internal static string msgNaoHaVagasVan {
            get {
                return ResourceManager.GetString("msgNaoHaVagasVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há veículos do tipo Van para retirar.
        ///.
        /// </summary>
        internal static string msgNaoHaVanParaRetirar {
            get {
                return ResourceManager.GetString("msgNaoHaVanParaRetirar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação: Eu não realizei validações para entradas diferentes de números. Não era o objetivo !!
        ///.
        /// </summary>
        internal static string msgObservacaoValidacoes {
            get {
                return ResourceManager.GetString("msgObservacaoValidacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops! Infelizmente eu não realizei validações para entradas diferentes de números.
        ///.
        /// </summary>
        internal static string msgOps {
            get {
                return ResourceManager.GetString("msgOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantas vagas para os Carros?.
        /// </summary>
        internal static string msgQuantasVagasCarros {
            get {
                return ResourceManager.GetString("msgQuantasVagasCarros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de vagas do estacionamento configurada com sucesso!
        ///.
        /// </summary>
        internal static string msgQuantasVagasEstacionamento {
            get {
                return ResourceManager.GetString("msgQuantasVagasEstacionamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantas vagas para as Motos?.
        /// </summary>
        internal static string msgQuantasVagasMotos {
            get {
                return ResourceManager.GetString("msgQuantasVagasMotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantas vagas para as Vans?.
        /// </summary>
        internal static string msgQuantasVagasVans {
            get {
                return ResourceManager.GetString("msgQuantasVagasVans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restam: {0} vaga(s), sendo:.
        /// </summary>
        internal static string msgRestamVagas {
            get {
                return ResourceManager.GetString("msgRestamVagas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 - Retirar carro.
        /// </summary>
        internal static string msgRetirarCarro {
            get {
                return ResourceManager.GetString("msgRetirarCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Retirar moto.
        /// </summary>
        internal static string msgRetirarMoto {
            get {
                return ResourceManager.GetString("msgRetirarMoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - Retirar Van.
        /// </summary>
        internal static string msgRetirarVan {
            get {
                return ResourceManager.GetString("msgRetirarVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o tipo de serviço para o estacionamento:
        ///.
        /// </summary>
        internal static string msgSelecioneTipoServico {
            get {
                return ResourceManager.GetString("msgSelecioneTipoServico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Status atual do estacionamento:.
        /// </summary>
        internal static string msgStatusEstacionamento {
            get {
                return ResourceManager.GetString("msgStatusEstacionamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaga(s) de carros: {0} de {1}.
        /// </summary>
        internal static string msgStatusVagasCarro {
            get {
                return ResourceManager.GetString("msgStatusVagasCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaga(s) de motos: {0} de {1}.
        /// </summary>
        internal static string msgStatusVagasMoto {
            get {
                return ResourceManager.GetString("msgStatusVagasMoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaga(s) de vans: {0} de {1}
        ///.
        /// </summary>
        internal static string msgStatusVagasVan {
            get {
                return ResourceManager.GetString("msgStatusVagasVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&apos;(
        ///.
        /// </summary>
        internal static string msgTriste {
            get {
                return ResourceManager.GetString("msgTriste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja utilizar outro serviço? (1- Sim ou 2- Não).
        /// </summary>
        internal static string msgUtilizarOutroServico {
            get {
                return ResourceManager.GetString("msgUtilizarOutroServico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vaga(s) esclusiva(s) de Carro e.
        /// </summary>
        internal static string msgVagasExclusivasCarros {
            get {
                return ResourceManager.GetString("msgVagasExclusivasCarros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vaga(s) esclusiva(s) de Moto,.
        /// </summary>
        internal static string msgVagasExclusivasMotos {
            get {
                return ResourceManager.GetString("msgVagasExclusivasMotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vaga(s) exclusiva(s) de Van.
        /// </summary>
        internal static string msgVagasExclusivasVans {
            get {
                return ResourceManager.GetString("msgVagasExclusivasVans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Van foi estacionado na vaga de Carro.
        ///.
        /// </summary>
        internal static string msgVanEstacionadaVagaCarro {
            get {
                return ResourceManager.GetString("msgVanEstacionadaVagaCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Van foi estacionado na vaga de Van.
        ///.
        /// </summary>
        internal static string msgVanEstacionadaVagaVan {
            get {
                return ResourceManager.GetString("msgVanEstacionadaVagaVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Van foi retirado da vaga de Carro.
        ///.
        /// </summary>
        internal static string msgVanRetiradaVagaCarro {
            get {
                return ResourceManager.GetString("msgVanRetiradaVagaCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um veículo do tipo Van foi retirado da vaga de Van.
        ///.
        /// </summary>
        internal static string msgVanRetiradaVagaVan {
            get {
                return ResourceManager.GetString("msgVanRetiradaVagaVan", resourceCulture);
            }
        }
    }
}
